###QUESTION 1

In [10]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
path= "/content/drive/MyDrive/dataminassi/assignment2/drinks.csv"
df = pd.read_csv(path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
a = df.groupby(['continent']).mean()
a

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

In [ ]:
max_index = a["wine_servings"].idxmax()
max_index
max_index = [df.groupby(['continent']).mean()]["wine_servings"].idxmax()

'EU'

In [ ]:
df.groupby(['continent'])["beer_servings"].describe()

           count        mean        std   min     25%    50%     75%    max
continent
AF          53.0   61.471698  80.557816   0.0   15.00   32.0   76.00  376.0
AS          44.0   37.045455  49.469725   0.0    4.25   17.5   60.50  247.0
EU          45.0  193.777778  99.631569   0.0  127.00  219.0  270.00  361.0
OC          16.0   89.687500  96.641412   0.0   21.00   52.5  125.75  306.0
SA          12.0  175.083333  65.242845  93.0  129.50  162.5  198.00  333.0

### QUESTION 2

In [5]:
path2= "/content/drive/MyDrive/dataminassi/assignment2/Euro_2012_stats_TEAM.csv"
df2 = pd.read_csv(path2)

first_column = df2.iloc[: , :1]
print(first_column)

                   Team
0               Croatia
1        Czech Republic
2               Denmark
3               England
4                France
5               Germany
6                Greece
7                 Italy
8           Netherlands
9                Poland
10             Portugal
11  Republic of Ireland
12               Russia
13                Spain
14               Sweden
15              Ukraine

In [ ]:
b = df2[df2["Goals"] > 5]
b[["Team","Shooting Accuracy"]]

        Team Shooting Accuracy
5    Germany             47.8%
7      Italy             43.0%
10  Portugal             34.3%
13     Spain             55.9%

In [ ]:
df2[["Goals"]].sum()

Goals    76
dtype: int64

In [9]:
df2[["Team","Goals"]].sort_values("Goals",ascending=False)

                   Team  Goals
13                Spain     12
5               Germany     10
7                 Italy      6
10             Portugal      6
3               England      5
6                Greece      5
12               Russia      5
14               Sweden      5
0               Croatia      4
1        Czech Republic      4
2               Denmark      4
4                France      3
8           Netherlands      2
9                Poland      2
15              Ukraine      2
11  Republic of Ireland      1

In [7]:
c = df2[df2["Red Cards"] == int(df2[["Red Cards"]].max())]
c

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17

### QUESTION 3

In [ ]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
cancer_dataset = pd.read_csv("/content/drive/MyDrive/dataminassi/assignment2/wdbc.csv" , header = None)
cancer_dataset

In [ ]:
x = cancer_dataset.drop(1 , axis = 1)
x

In [ ]:
y = cancer_dataset[1]
y

In [ ]:
y_new = []
for tumor in y:
    if (tumor == 'M'):
        y_new.append(1)
    else:
        y_new.append(0)
y_new = np.array(y_new)
y_new = y_new.reshape(-1, 1)
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y_new, test_size=0.2, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, info_gain=None, value=None):
        ''' constructor ''' 
        
        # for decision node
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
        self.info_gain = info_gain
        
        # for leaf node
        self.value = value

In [ ]:
class DecisionTreeClassifier():
    def __init__(self, min_samples_split=5, max_depth=10):
        ''' constructor '''
        
        # initialize the root of the tree 
        self.root = None
        
        # stopping conditions
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        
    def build_tree(self, dataset, curr_depth=0):
        ''' recursive function to build the tree ''' 
        
        X, Y = dataset[:,:-1], dataset[:,-1]
        num_samples, num_features = np.shape(X)
        
        # split until stopping conditions are met
        if num_samples >= self.min_samples_split and curr_depth <= self.max_depth:
            # find the best split
            best_split = self.get_best_split(dataset, num_samples, num_features)
            # check if information gain is positive
            if best_split["info_gain"] > 0:
                # recur left
                left_subtree = self.build_tree(best_split["dataset_left"], curr_depth+1)
                # recur right
                right_subtree = self.build_tree(best_split["dataset_right"], curr_depth+1)
                # return decision node
                return Node(best_split["feature_index"], best_split["threshold"], 
                            left_subtree, right_subtree, best_split["info_gain"])
        
        # compute leaf node
        leaf_value = self.calculate_leaf_value(Y)
        # return leaf node
        return Node(value=leaf_value)
    
    def get_best_split(self, dataset, num_samples, num_features):
        ''' function to find the best split '''
        
        # dictionary to store the best split
        best_split = {}
        max_info_gain = -float("inf")
        
        # loop over all the features
        for feature_index in range(num_features):
            feature_values = dataset[:, feature_index]
            possible_thresholds = np.unique(feature_values)
            # loop over all the feature values present in the data
            for threshold in possible_thresholds:
                # get current split
                dataset_left, dataset_right = self.split(dataset, feature_index, threshold)
                # check if childs are not null
                if len(dataset_left)>0 and len(dataset_right)>0:
                    y, left_y, right_y = dataset[:, -1], dataset_left[:, -1], dataset_right[:, -1]
                    # compute information gain
                    curr_info_gain = self.information_gain(y, left_y, right_y, "gini")
                    # update the best split if needed
                    if curr_info_gain>max_info_gain:
                        best_split["feature_index"] = feature_index
                        best_split["threshold"] = threshold
                        best_split["dataset_left"] = dataset_left
                        best_split["dataset_right"] = dataset_right
                        best_split["info_gain"] = curr_info_gain
                        max_info_gain = curr_info_gain
                        
        # return best split
        return best_split
    
    def split(self, dataset, feature_index, threshold):
        ''' function to split the data '''
        
        dataset_left = np.array([row for row in dataset if row[feature_index]<=threshold])
        dataset_right = np.array([row for row in dataset if row[feature_index]>threshold])
        return dataset_left, dataset_right
    
    def information_gain(self, parent, l_child, r_child, mode="entropy"):
        ''' function to compute information gain '''
        
        weight_l = len(l_child) / len(parent)
        weight_r = len(r_child) / len(parent)
        if mode=="gini":
            gain = self.gini_index(parent) - (weight_l*self.gini_index(l_child) + weight_r*self.gini_index(r_child))
        else:
            gain = self.entropy(parent) - (weight_l*self.entropy(l_child) + weight_r*self.entropy(r_child))
        return gain
    
    def entropy(self, y):
        ''' function to compute entropy '''
        
        class_labels = np.unique(y)
        entropy = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            entropy += -p_cls * np.log2(p_cls)
        return entropy
    
    def gini_index(self, y):
        ''' function to compute gini index '''
        
        class_labels = np.unique(y)
        gini = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            gini += p_cls**2
        return 1 - gini
        
    def calculate_leaf_value(self, Y):
        ''' function to compute leaf node '''
        
        Y = list(Y)
        return max(Y, key=Y.count)
    
    def print_tree(self, tree=None, indent=" "):
        ''' function to print the tree '''
        
        if not tree:
            tree = self.root

        if tree.value is not None:
            print(tree.value)

        else:
            print("X_"+str(tree.feature_index), "<=", tree.threshold, "?", tree.info_gain)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)
    
    def fit(self, X, Y):
        ''' function to train the tree '''
        
        dataset = np.concatenate((X, Y), axis=1)
        self.root = self.build_tree(dataset)
    
    def predict(self, X):
        ''' function to predict new dataset '''
        
        preditions = [self.make_prediction(x, self.root) for x in X]
        return preditions
    
    def make_prediction(self, x, tree):
        ''' function to predict a single data point '''
        
        if tree.value!=None: return tree.value
        feature_val = x[tree.feature_index]
        if feature_val<=tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)

In [ ]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

In [ ]:
entropy_value = classifier.entropy(y)
entropy_value

In [ ]:
y_pred = classifier.predict(x_test) 
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)